### ISSUE TITLE
Build binding pocket datasets for training

### ISSUE THREAD

**Issue by jyaacoub** [jyaacoub/MutDTA#123]
# Goal/Tasks
Ideally we would want to just take our existing dataset, apply some method to convert it from a "full sequence" db to a "pocket sequence db". This means minimal changes to our `src/data_prep/dataset.py` script.

Some general tasks for this
- [x] Download binding pocket data for the target db from KLIFS
- [x] Create graph masks using pocket alignment tool created for #110
- [x] Apply mask to protein graphs in `data_pro.pt` (dict of Pytorch Data objects) to only include pocket (make sure to keep the full sequence for esm)
- [x] If there are any proteins that do not have pocket sequences they must be removed from the dataset, this means also modifying the `cleaned_XY.csv` file to remove all proteins that do not have pocket sequences. (lmk at this stage how many you find, if there are a lot that are missing then we might need to do something else).
- [x] (optionally) repeat this for all dataset subsets and save the new dataset under a new `data_root` (e.g.: `{path}/DavisKibaDataset/davis/` to `{path}/DavisKibaDataset/davis_pocket/` (see [Dataset](#Dataset) below)

# Scope
## Relevant files
The datasets are organized with the following files
```bash
> ls nomsa_binary_original_binary/full/
cleaned_XY.csv  data_mol.pt  data_pro.pt  pre_filter.pt  pre_transform.pt  XY.csv
```
For the method itself you can just work in the [`pocket_alignment.py`](https://github.com/jyaacoub/MutDTA/blob/main/src/utils/pocket_alignment.py) script and I will send you a sample directory  with the `data_pro.pt` file to run on.

## Dataset
For this we will start by just focusing on the simplist dataset - **davis** with `nomsa_binary_original_binary` which can be loaded up/created with the following (but you likely dont need to bother with this in order to resolve this issue):
```python
from src.data_prep.datasets import DavisKibaDataset
dataset = DavisKibaDataset(
        save_root=f'{path}/DavisKibaDataset/davis/', # path to created dataset
        data_root=f'{path}/davis/', # path to raw data
        feature_opt='nomsa',
        edge_opt='binary',
        subset='full',
        ligand_feature='original',
        ligand_edge='binary')
```

**Comment by JacksonH44** [comment]
Mutation site data of the form {gene}({ref}{pos}{mut}) in Davis may be incorrect at the source (https://github.com/hkmztrk/DeepDTA/blob/master/data/davis/proteins.txt)

**Comment by JacksonH44** [comment]
Data that's saved in data/DavisKibaDataset/davis_pocket has seqeunces that aren't the mutated versions of the sequence, this is the same for the original davis dataset. I basically just used the base gene name as the key for what to download from KLIFS because KLIFS doesn't handle mutated AA sequences. Also I stripped -{beta,alpha,gamma,delta} tags from genes as well as descriptor tags (e.g., RSK1(KinDom.2-C-terminal) would just be treated as RSK1 when downloading the binding pocket sequence).

**Comment by JacksonH44** [comment]
Couldn't find binding pockets in KLIFS for:
9 genes in KIBA
43 genes in DAVIS
